import asyncio
import json
from pathlib import Path

import server
from mcp import Client
from mcp.client.stdio import StdioServerParameters

REPO = Path(__file__).resolve().parents[1]
MODEL = REPO / "example" / "production_planning.mzn"
DATA = {
    "nproducts": 2,
    "profit": [400, 450],
    "pname": ["banana-cake", "chocolate-cake"],
    "nresources": 5,
    "capacity": [4000, 6, 2000, 500, 500],
    "rname": ["flour", "banana", "sugar", "butter", "cocoa"],
    "consumption": [[250, 2, 75, 100, 0], [200, 0, 150, 150, 75]],
}
TOOL_NAMES = {
    "list_solvers",
    "list_tools",
    "validate_model",
    "solve_model",
    "compare_solvers",
    "solve_model_by_path",
    "get_model_info",
    "get_flatzinc",
}
PARAMS = StdioServerParameters(command="uv", args=["run", "minizinc-mcp"], cwd=str(REPO))


def run(coro):
    return asyncio.run(coro)


async def tool(name, arguments=None):
    async with Client(PARAMS) as client:
        result = await client.call_tool(name, arguments)
        return "\n".join(part.text for part in result.content if hasattr(part, "text"))


async def tool_names():
    async with Client(PARAMS) as client:
        names = await client.list_tools()
        return {t.name for t in names.tools}


def test_tools_are_registered():
    names = run(tool_names())
    assert TOOL_NAMES <= names


def test_list_tools():
    out = run(tool("list_tools"))
    assert set(out.splitlines()) == TOOL_NAMES


def test_list_solvers():
    assert "gecode" in run(tool("list_solvers"))


def test_validate_model():
    assert "VALID" in run(tool("validate_model", {"model_code": MODEL.read_text()}))


def test_solve_model():
    out = run(tool("solve_model", {"model_code": MODEL.read_text(), "params": DATA}))
    assert "OPTIMAL_SOLUTION" in out
    assert '"objective": 1700' in out


def test_compare_solvers_forwards_each_run(monkeypatch):
    calls = []

    def fake_solve_model(**kwargs):
        calls.append(kwargs)
        return {"status": "SATISFIED", "solver": kwargs["solver"]}

    monkeypatch.setattr(server, "solve_model", fake_solve_model)
    result = server.compare_solvers(
        model_code="var 1..3: x; solve satisfy;",
        solvers=["gecode", "chuffed"],
        params={"limit": 3},
        all_solutions=False,
        max_solutions=1,
        timeout_seconds=5,
    )

    assert result == {
        "results": {
            "gecode": {"status": "SATISFIED", "solver": "gecode"},
            "chuffed": {"status": "SATISFIED", "solver": "chuffed"},
        }
    }
    assert calls == [
        {
            "model_code": "var 1..3: x; solve satisfy;",
            "params": {"limit": 3},
            "solver": solver,
            "all_solutions": False,
            "max_solutions": 1,
            "timeout_seconds": 5,
        }
        for solver in ["gecode", "chuffed"]
    ]


def test_compare_solvers_preserves_individual_errors():
    out = run(
        tool(
            "compare_solvers",
            {
                "model_code": MODEL.read_text(),
                "params": DATA,
                "solvers": ["gecode", "missing-test-solver"],
            },
        )
    )
    result = json.loads(out)["results"]

    assert result["gecode"]["status"] == "OPTIMAL_SOLUTION"
    assert result["gecode"]["objective"] == 1700
    assert result["missing-test-solver"]["status"] == "ERROR"


def test_solve_model_by_path():
    data_path = REPO / "example" / "production_planning.dzn"
    out = run(tool("solve_model_by_path", {"model_path": str(MODEL), "data_path": str(data_path)}))
    assert "OPTIMAL_SOLUTION" in out
    assert '"objective": 1700' in out


def test_get_model_info():
    out = run(tool("get_model_info", {"model_code": MODEL.read_text()}))
    assert '"method": "maximize"' in out
    assert '"nproducts"' in out
    assert '"profit"' in out
    assert '"capacity"' in out
    assert '"consumption"' in out
    assert '"produce"' in out


def test_get_flatzinc():
    out = run(tool("get_flatzinc", {"model_code": MODEL.read_text(), "params": DATA}))
    assert '"flat_model"' in out
    assert 'of var ' in out
    assert 'Generated by MiniZinc' in out
    assert '"statistics"' in out